# Site settings
title: An Exploration of The Power Of Connected
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is an exploration of the power of connected data, and how the relationships between data can be as powerful as the values themselves.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.powerofconnecteddata.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  connecteddata

# Build settings
markdown: kramdown
